# Generated by Django 4.0.4 on 2022-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='godina_rodjenja',
            field=models.IntegerField(db_column='Godina_rodjenja', null=True),
        ),
    ]
