version: '3'
services:
  auth_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3310:3306
    volumes:
      - auth_db_vol:/var/lib/mysql
    networks:
      - auth_net
  shop_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3311:3306
    volumes:
      - shop_db_vol:/var/lib/mysql
    networks:
      - shop_net
      - admin_net
      - customer_net
      - daemon_net
  paradajz:
    image: paradajz
    build:
      context: .
      dockerfile: paradajz/Dockerfile
    networks:
      - auth_net
  krastavac:
    image: krastavac
    build:
      context: .
      dockerfile: krastavac/Dockerfile
    networks:
      - shop_net
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - daemon_net
      - warehouse_net
  authentication:
    image: authentication
    build:
      context: .
      dockerfile: authentication/Dockerfile
    networks:
      - auth_net
    ports:
      - 5001:5001
  warehouse:
    image: warehouse
    build:
      context: .
      dockerfile: warehouse/Dockerfile
    deploy:
      replicas: 3
    networks:
      - warehouse_net
    ports:
      - 5002:5002
  daemon:
    image: daemon
    build:
      context: .
      dockerfile: daemon/Dockerfile
    networks:
      - daemon_net
  customer:
    image: customer
    build:
      context: .
      dockerfile: customer/Dockerfile
    deploy:
      replicas: 3
    networks:
      - customer_net
    ports:
      - 5003:5003
  admin:
    image: admin
    build:
      context: .
      dockerfile: admin/Dockerfile
    networks:
      - admin_net
    ports:
      - 5004:5004

volumes:
  auth_db_vol:
  shop_db_vol:

networks:
  auth_net:
  shop_net:
  admin_net:
  customer_net:
  warehouse_net:
  daemon_net:
