# Generated by Django 4.0.4 on 2022-07-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenovnikNocenja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_broj_nocenja', models.IntegerField()),
                ('max_broj_nocenja', models.IntegerField()),
                ('cena_po_nocenju', models.IntegerField()),
            ],
            options={
                'db_table': 'CenovnikNocenja',
            },
        ),
        migrations.CreateModel(
            name='DodatnaAktivnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
            ],
            options={
                'db_table': 'DodatnaAktivnost',
            },
        ),
        migrations.CreateModel(
            name='RaftingPutanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
            ],
            options={
                'db_table': 'RaftingPutanja',
            },
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosilac_prijave', models.CharField(max_length=100)),
                ('broj_nocenja', models.IntegerField()),
                ('broj_gostiju', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('obuhvata', models.ManyToManyField(to='rafting.dodatnaaktivnost')),
                ('rafting_putanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.raftingputanja')),
            ],
            options={
                'db_table': 'Prijava',
            },
        ),
    ]
