# Generated by Django 4.0.4 on 2022-06-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id_dog', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=32)),
                ('datum', models.DateField()),
                ('vreme', models.TimeField()),
                ('broj_interesenata', models.IntegerField()),
                ('je_otkazan', models.IntegerField()),
            ],
            options={
                'db_table': 'dogadjaj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('ime_grada', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('naziv', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kategorija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_lokacije', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=32)),
                ('max_kapacitet', models.IntegerField()),
            ],
            options={
                'db_table': 'lokacija',
                'managed': False,
            },
        ),
    ]
